force_arm:
  target:
    entity:
      integration: ajax
      domain: alarm_control_panel

force_arm_night:
  target:
    entity:
      integration: ajax
      domain: alarm_control_panel

get_raw_devices:

refresh_metadata:
