blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Ask questions about Home Assistant in general
  - name: Ajax Systems Support
    url: https://support.ajax.systems/
    about: For issues with your Ajax hardware or Ajax app
